"""initial

Revision ID: 171bbe9d0e08
Revises: 
Create Date: 2026-04-25 15:57:22.051433

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '171bbe9d0e08'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS \"SHR_V1\"")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='SHR_V1'
    )
    op.create_index(op.f('ix_SHR_V1_users_email'), 'users', ['email'], unique=True, schema='SHR_V1')
    op.create_index(op.f('ix_SHR_V1_users_id'), 'users', ['id'], unique=False, schema='SHR_V1')
    op.create_index(op.f('ix_SHR_V1_users_username'), 'users', ['username'], unique=True, schema='SHR_V1')
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['SHR_V1.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='SHR_V1'
    )
    op.create_index(op.f('ix_SHR_V1_contacts_id'), 'contacts', ['id'], unique=False, schema='SHR_V1')
    op.create_index('ix_contacts_user_id', 'contacts', ['user_id'], unique=False, schema='SHR_V1')
    op.create_index('ix_contacts_user_phone', 'contacts', ['user_id', 'phone_number'], unique=False, schema='SHR_V1')
    op.create_table('groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['SHR_V1.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='SHR_V1'
    )
    op.create_index(op.f('ix_SHR_V1_groups_id'), 'groups', ['id'], unique=False, schema='SHR_V1')
    op.create_index('ix_groups_user_id', 'groups', ['user_id'], unique=False, schema='SHR_V1')
    op.create_index('ix_groups_user_name', 'groups', ['user_id', 'name'], unique=False, schema='SHR_V1')
    op.create_table('reminder_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('audio_filename', sa.Text(), nullable=False),
    sa.Column('recurrence', sa.String(length=20), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('retry_gap_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['SHR_V1.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='SHR_V1'
    )
    op.create_index(op.f('ix_SHR_V1_reminder_templates_id'), 'reminder_templates', ['id'], unique=False, schema='SHR_V1')
    op.create_index('ix_reminder_templates_user_id', 'reminder_templates', ['user_id'], unique=False, schema='SHR_V1')
    op.create_table('group_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['SHR_V1.contacts.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['SHR_V1.groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'contact_id', name='uq_group_member'),
    schema='SHR_V1'
    )
    op.create_table('reminders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('scheduled_time', sa.DateTime(), nullable=False),
    sa.Column('audio_filename', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('recurrence', sa.String(length=20), nullable=True),
    sa.Column('recurrence_end_date', sa.DateTime(), nullable=True),
    sa.Column('call_sid', sa.String(length=50), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('retry_gap_minutes', sa.Integer(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('parent_reminder_id', sa.Integer(), nullable=True),
    sa.Column('system_retry_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('feedback_rating', sa.Integer(), nullable=True),
    sa.Column('feedback_comment', sa.Text(), nullable=True),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('fallback_text', sa.Text(), nullable=True),
    sa.Column('fallback_sent', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('preferred_language', sa.String(length=10), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['SHR_V1.groups.id'], ),
    sa.ForeignKeyConstraint(['parent_reminder_id'], ['SHR_V1.reminders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['SHR_V1.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='SHR_V1'
    )
    op.create_index(op.f('ix_SHR_V1_reminders_id'), 'reminders', ['id'], unique=False, schema='SHR_V1')
    op.create_index('ix_reminders_group_id', 'reminders', ['group_id'], unique=False, schema='SHR_V1')
    op.create_index('ix_reminders_status_scheduled', 'reminders', ['status', 'scheduled_time'], unique=False, schema='SHR_V1')
    op.create_index('ix_reminders_status_updated', 'reminders', ['status', 'updated_at'], unique=False, schema='SHR_V1')
    op.create_index('ix_reminders_user_id', 'reminders', ['user_id'], unique=False, schema='SHR_V1')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reminders_user_id', table_name='reminders', schema='SHR_V1')
    op.drop_index('ix_reminders_status_updated', table_name='reminders', schema='SHR_V1')
    op.drop_index('ix_reminders_status_scheduled', table_name='reminders', schema='SHR_V1')
    op.drop_index('ix_reminders_group_id', table_name='reminders', schema='SHR_V1')
    op.drop_index(op.f('ix_SHR_V1_reminders_id'), table_name='reminders', schema='SHR_V1')
    op.drop_table('reminders', schema='SHR_V1')
    op.drop_table('group_members', schema='SHR_V1')
    op.drop_index('ix_reminder_templates_user_id', table_name='reminder_templates', schema='SHR_V1')
    op.drop_index(op.f('ix_SHR_V1_reminder_templates_id'), table_name='reminder_templates', schema='SHR_V1')
    op.drop_table('reminder_templates', schema='SHR_V1')
    op.drop_index('ix_groups_user_name', table_name='groups', schema='SHR_V1')
    op.drop_index('ix_groups_user_id', table_name='groups', schema='SHR_V1')
    op.drop_index(op.f('ix_SHR_V1_groups_id'), table_name='groups', schema='SHR_V1')
    op.drop_table('groups', schema='SHR_V1')
    op.drop_index('ix_contacts_user_phone', table_name='contacts', schema='SHR_V1')
    op.drop_index('ix_contacts_user_id', table_name='contacts', schema='SHR_V1')
    op.drop_index(op.f('ix_SHR_V1_contacts_id'), table_name='contacts', schema='SHR_V1')
    op.drop_table('contacts', schema='SHR_V1')
    op.drop_index(op.f('ix_SHR_V1_users_username'), table_name='users', schema='SHR_V1')
    op.drop_index(op.f('ix_SHR_V1_users_id'), table_name='users', schema='SHR_V1')
    op.drop_index(op.f('ix_SHR_V1_users_email'), table_name='users', schema='SHR_V1')
    op.drop_table('users', schema='SHR_V1')
    # ### end Alembic commands ###
