"""minor changes

Revision ID: 6e83b95c9425
Revises: 0001
Create Date: 2026-04-20 17:54:05.130164

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '6e83b95c9425'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reminders_id', table_name='reminders', schema='SHR_V1')
    op.create_index(op.f('ix_SHR_V1_reminders_id'), 'reminders', ['id'], unique=False, schema='SHR_V1')
    op.drop_index('ix_users_email', table_name='users', schema='SHR_V1')
    op.drop_index('ix_users_id', table_name='users', schema='SHR_V1')
    op.drop_index('ix_users_username', table_name='users', schema='SHR_V1')
    op.create_index(op.f('ix_SHR_V1_users_email'), 'users', ['email'], unique=True, schema='SHR_V1')
    op.create_index(op.f('ix_SHR_V1_users_id'), 'users', ['id'], unique=False, schema='SHR_V1')
    op.create_index(op.f('ix_SHR_V1_users_username'), 'users', ['username'], unique=True, schema='SHR_V1')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_SHR_V1_users_username'), table_name='users', schema='SHR_V1')
    op.drop_index(op.f('ix_SHR_V1_users_id'), table_name='users', schema='SHR_V1')
    op.drop_index(op.f('ix_SHR_V1_users_email'), table_name='users', schema='SHR_V1')
    op.create_index('ix_users_username', 'users', ['username'], unique=True, schema='SHR_V1')
    op.create_index('ix_users_id', 'users', ['id'], unique=False, schema='SHR_V1')
    op.create_index('ix_users_email', 'users', ['email'], unique=True, schema='SHR_V1')
    op.drop_index(op.f('ix_SHR_V1_reminders_id'), table_name='reminders', schema='SHR_V1')
    op.create_index('ix_reminders_id', 'reminders', ['id'], unique=False, schema='SHR_V1')
    # ### end Alembic commands ###
