"""add groups tables

Revision ID: 70e39526dfb1
Revises: 8b784f211aa0
Create Date: 2026-04-23 16:35:16.188236

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '70e39526dfb1'
down_revision: Union[str, None] = '8b784f211aa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['SHR_V1.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='SHR_V1'
    )
    op.create_index(op.f('ix_SHR_V1_groups_id'), 'groups', ['id'], unique=False, schema='SHR_V1')
    op.create_index('ix_groups_user_id', 'groups', ['user_id'], unique=False, schema='SHR_V1')
    op.create_table('group_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['SHR_V1.contacts.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['SHR_V1.groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'contact_id', name='uq_group_member'),
    schema='SHR_V1'
    )
    op.add_column('reminders', sa.Column('group_id', sa.Integer(), nullable=True), schema='SHR_V1')
    op.create_foreign_key(None, 'reminders', 'groups', ['group_id'], ['id'], source_schema='SHR_V1', referent_schema='SHR_V1')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reminders', schema='SHR_V1', type_='foreignkey')
    op.drop_column('reminders', 'group_id', schema='SHR_V1')
    op.drop_table('group_members', schema='SHR_V1')
    op.drop_index('ix_groups_user_id', table_name='groups', schema='SHR_V1')
    op.drop_index(op.f('ix_SHR_V1_groups_id'), table_name='groups', schema='SHR_V1')
    op.drop_table('groups', schema='SHR_V1')
    # ### end Alembic commands ###
