"""add contact tables

Revision ID: 8b784f211aa0
Revises: 8bd4417e95bd
Create Date: 2026-04-23 16:12:06.685265

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '8b784f211aa0'
down_revision: Union[str, None] = '8bd4417e95bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['SHR_V1.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='SHR_V1'
    )
    op.create_index(op.f('ix_SHR_V1_contacts_id'), 'contacts', ['id'], unique=False, schema='SHR_V1')
    op.create_index('ix_contacts_user_id', 'contacts', ['user_id'], unique=False, schema='SHR_V1')
    op.create_index(op.f('ix_SHR_V1_reminder_templates_id'), 'reminder_templates', ['id'], unique=False, schema='SHR_V1')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_SHR_V1_reminder_templates_id'), table_name='reminder_templates', schema='SHR_V1')
    op.drop_index('ix_contacts_user_id', table_name='contacts', schema='SHR_V1')
    op.drop_index(op.f('ix_SHR_V1_contacts_id'), table_name='contacts', schema='SHR_V1')
    op.drop_table('contacts', schema='SHR_V1')
    # ### end Alembic commands ###
