"""added feedback column

Revision ID: c724df95c42a
Revises: 6e83b95c9425
Create Date: 2026-04-20 18:04:14.200708

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'c724df95c42a'
down_revision: Union[str, None] = '6e83b95c9425'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminders', sa.Column('feedback_rating', sa.Integer(), nullable=True), schema='SHR_V1')
    op.add_column('reminders', sa.Column('feedback_comment', sa.Text(), nullable=True), schema='SHR_V1')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reminders', 'feedback_comment', schema='SHR_V1')
    op.drop_column('reminders', 'feedback_rating', schema='SHR_V1')
    # ### end Alembic commands ###
