name: Build & Deploy Backend

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: smartreminderregistry.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: smartreminderregistry.azurecr.io/smart-reminder-backend:latest

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Restart Backend App Service
        uses: azure/cli@v2
        with:
          inlineScript: |
            az webapp restart --resource-group SHR-DEV --name smart-reminder

      - name: Restart Celery Worker App Service
        uses: azure/cli@v2
        with:
          inlineScript: |
            az webapp restart --resource-group SHR-DEV --name SHR-worker

      - name: Restart Celery Beat App Service
        uses: azure/cli@v2
        with:
          inlineScript: |
            az webapp restart --resource-group SHR-DEV --name SHR-beat
